format: json
filename: delplister
allowed:
  - js
  - ts
  - jsx
  - tsx
notallowed:
  - d.ts
ignore:
  - node_modules
  - dist
include:
  - src
  - lib
rules:
  - type: CallExpression
    name:
      - Ext.define
    argument: 1
    rules:
      - type: ObjectLiteralExpression
        properties:
          - extend
          - override
          - modelName
          - views
          - models
          - stores
